name:
  max_length: 50
email:
  max_length: 250
password:
  min_length: 6
user_size:
  size: 80
session_number: 1
avatar_size: 50
host: "localhost:3000"
number_session: 1
account_activation: "Account activation"
email_com: "noreply@example.com"
password_reset: "Password reset"
remember_me: 1
account_activation: "Account activation"
